---
title: "Enrollment Drops 2018-2019"
author: "Shafi Rubbani"
date: "2/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(dplyr)
library(ggplot2)
library(gt)
library(readxl)
library(janitor)

download.file("https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_03.06.18.xlsx",
              destfile = "spring_2018.xlsx",
              mode = "wb"
              )

download.file("https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_2.28.19.xlsx",
              destfile = "spring_2019.xlsx",
              mode = "wb")

spring_2018 <- read_excel("spring_2018.xlsx", skip = 2) %>%
  clean_names() %>% 
  filter(!is.na(course_name)) %>% 
  select(course_id, course_title, course_name, u_grad)
  
spring_2019 <- read_excel("spring_2019.xlsx", skip = 3) %>% 
  clean_names() %>% 
  filter(!is.na(course_name)) %>% 
  select(course_id, course_title, course_name, u_grad)

```

```{r join_data}

spring_enrollment <- spring_2019 %>% 
  inner_join(spring_2018, by = c("course_id"), suffix = c(".2019", ".2018"))

```

```{r enrollment_drops}

spring_enrollment %>% 
  mutate(change = u_grad.2019 - u_grad.2018) %>% 
  select(course_title.2019, course_name.2019, u_grad.2018, u_grad.2019, change) %>% 
  arrange(change) %>% 
  slice(1:10) %>% 

gt %>% 
  tab_header(title = "Biggest Enrollment Decreases in Spring 2019") %>% 
  cols_label(course_title.2019 = "Number",
              course_name.2019 = "Name",
              u_grad.2019 = "2019",
              u_grad.2018 = "2018",
              change = "Change") %>% 
  tab_source_note("Data from the Harvard Registrar") #%>% 
  #as_raw_html() %>% as.character() %>% cat()

```

***

```{r biggest_new}
spring_new <- spring_2019 %>%
  anti_join(spring_2018, by = c("course_id"))

spring_new %>%  
  select(course_title, course_name, u_grad) %>% 
  arrange(desc(u_grad)) %>% 
  slice(1:10) %>% 
  
gt %>% 
  tab_header(title = "Biggest New Classes in Spring 2019") %>% 
  cols_label(course_title = "Number",
              course_name = "Name",
              u_grad = "Undergraduate Enrollment") %>% 
  tab_source_note("Data from the Harvard Registrar") #%>% 
  #as_raw_html() %>% as.character() %>% cat()
```